Added wizard for subscribing attendees
antonag32/opa pull request #2
Opened 2022-03-24 01:12 UTC by antonag32

Completed all exercises under the 'wizard' section.

2022-03-25 21:08 UTC, frahikLV commented
@antonag32 could you rebase this PR?, please

2022-03-25 23:15 UTC, antonag32 commented
@frahikLV Rebased

2022-03-28 17:42 UTC, frahikLV requested changes
@antonag32 can you address this change?

2022-03-28 17:42 UTC, frahikLV commented on opa/security/ir.model.access.csv
> +attendee_wizard_all,opa.attendee.wizard.all,model_attendee_wizard,opa.group_manager,1,1,1,0
@antonag32 Wizards didn't require access rules, if you want that only manager can view it, on menu give access only to that group

2022-03-28 19:10 UTC, antonag32 commented on opa/security/ir.model.access.csv
> +attendee_wizard_all,opa.attendee.wizard.all,model_attendee_wizard,opa.group_manager,1,1,1,0
If I don't add an access rule I get the following warning:
```
2022-03-28 19:03:59,017 6066 WARNING opatest odoo.modules.loading: The models ['attendee.wizard'] have no access rules in module opa, consider adding some, like:
id,name,model_id:id,group_id:id,perm_read,perm_write,perm_create,perm_unlink
opa.access_attendee_wizard,access_attendee_wizard,opa.model_attendee_wizard,base.group_user,1,0,0,0 
```
And I am also unable to access the wizard, as I no longer see it on the 'Action' drop down menu. I reviewed some of the original Odoo modules and I also see they add access rules for wizards (for example in `account` for the model `account.automatic.entry.wizard`).
Based on this I think the access rule is necessary.

2022-03-28 19:35 UTC, merged